#!/bin/bash
# set -x

F=v9kramtest
BASE=`dirname $0`

export BREAK=${BREAK:-marchu_1seg_nostack marchu_4k}
export SECTS=".lib .text .resetvec .rodata"

YELLOW="\033[33m"
BOLD="\033[1m"
RESET="\033[0m"

VERSION=`git describe --tags --always --dirty=-local --broken=-XX 2>/dev/null || echo local_build`
echo "db \"$VERSION\"" > version.inc

# nasm -f dbg -iinc $F.asm -o $F.i -l $F.lst || exit -1
# nasm -MG -MP -MF $F.dep -iinc $F.asm || exit -1
nasm -o $F.bin -iinc $F.asm -l $F.lst -Lm || exit -1
$BASE/size $F.map
# $BASE/makerom $F.bin > $F.32k || exit -1

# set up a debugscript with breakpoints
#$BASE/make_debugscript $F.map > $F.debug || exit -1
# sha1sum $F.32k
set +x
echo
echo -e "Version: $BOLD$YELLOW$VERSION$RESET"
echo

split -b 4k $F.bin "$F"_
mv "$F"_aa "$F"_FE.bin
mv "$F"_ab "$F"_FF.bin

bin2hex -q -o $F.hex $F.bin
bin2hex -q -o "$F"_FE.hex "$F"_FE.bin
bin2hex -q -o "$F"_FF.hex "$F"_FF.bin
# code: language=bash tabSize=8
