#!/bin/bash
BASE=`dirname $0`
$BASE/build || exit -1

# if [ "x$DEBUG" == "x" ]; then
# 	DEBUG=''
# else
# 	DEBUG='-debug'
# fi

F=v9kramtest
FE_NAME="v9000 univ. fe f3f7 13db.7j"
FF_NAME="v9000 univ. ff f3f7 39fe.8j"
ROMS="$HOME/.mame/roms"

RAM=${RAM:-256K}

MOPTS="victor9k -ramsize $RAM"
VOPTS="-window -resolution 800x600 -nofilter -nokeepaspect"
SOPTS="-rs232a null_modem -bitb socket.localhost:7201"
ROPTS="-skip_gameinfo -cheat -nomouse -volume -20"
DOPTS="-debug -update_in_pause -debugscript $F.debug"

set -x
rm -f comments/victor9k.cmt
cp "$F"_FE.bin ~/.mame/roms/victor9k/"$FE_NAME"
cp "$F"_FF.bin ~/.mame/roms/victor9k/"$FF_NAME"
mame $MOPTS -rompath $ROMS $ROPTS $DOPTS $VOPTS $SOPTS $*